apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: prom-label-proxy-client
rules:
- apiGroups: [""]
  resources: ["node/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prom-label-proxy-client
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prom-label-proxy-client
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
